- .eslintrc.js
- app/src/api/balances.js
- app/src/api/markets.js
- app/src/api/utils/positions.js
- app/src/api/web3.js
- app/src/components/MarketAssumption/index.js
- app/src/components/MarketAssumptions/index.js
- app/src/components/Markets/index.js
- app/src/components/Page/index.js
- app/src/containers/Page/index.js
- app/src/index.js
- migrations/2_pmSystem_migration.js
- package-lock.json
- package.json
- Add eslint plugin for react
- Add `eval-source-map` in webpack for easier debugging
- Add `sellOutcomes` function
- Get rid of `factoryNonce` in migration script and use `initialNonce`. We used it only once but the previous code incremented it for some reason (why? maybe I misunderstand something)
The main changes are in:
- `/containers/Page/index.js`
- `/src/api/markets.js`
> Add selling functionality, run prettier on few files, add source maps

- app/src/components/BuySection/index.js
- app/src/components/Page/index.js
- app/src/containers/Page/index.js
Forgive for I have <s>sinned</s> copy-pasted code from `YourPositions/index.js`.
But seriously, I figured you were touching that file @andre-meyer so we can handle refactoring that after you're done.
> Staged positions

- app/src/api/markets.js
> await depositing fn and make approve transaction

- README.md
- contracts/DifficultyOracle.sol
- contracts/ETHValueOracle.sol
- contracts/GasLimitOracle.sol
- package-lock.json
I have updated the oracles with some small changes as Alan requested in the audit.
I wanted to make sure that everything was still in-tact by running the tests that were prepared for the oracles, but it seems the deployment script was changed and now those tests don’t work anymore…I don’t really know a simple way to make them work again. Could someone that knows please make sure to run the tests on the oracles before launch.
> Oracle audit changes

- app/config.json
- app/config.json.mainnet
- markets.config.js
I put the Mainnet and Rinkeby configs in here.
> Deploy new markets

- .travis.yml
- Add travis CI file for development deployment
> Add travis CI file

- .travis.yml
- app/config.json
- app/src/Modals/Connect.js
- app/src/Root/index.js
- app/src/Sidebar/Buy/index.js
- app/src/components/Footer/footer.scss
- app/src/components/Menu.js
- app/src/components/menu.scss
- app/src/utils/web3.js
- package-lock.json
- package.json
- truffle-config.js
Add latest changes added in alpha branch to development branch.
Avoid merging market configuration for demo.
> Merge latest alpha fixes to development

- app/config.local.json.bak
- app/src/MarketTable/MarketRow/OutcomeSelection.js
- app/src/MarketTable/MarketRow/OutcomeSelection.scss
- app/src/MarketTable/MarketRow/index.js
- app/src/MarketTable/index.js
- app/src/Sidebar/Positions/index.js
- app/src/Sidebar/Positions/positions.scss
- app/src/components/OutcomeCard.js
- app/src/components/outcomeCard.scss
- app/src/utils/collateral-info.js
- markets.config.js
- migrations/12_create_lmsr_mm.js
- migrations/utils/writeToConfig.js
- package-lock.json
- package.json
- Fix styling for "your positions"
- Add temporary "Any" position until logic in position merge is improved
- Improve Select for Position
- Fix "ETH" and "DAI" symbol things
> Various UI/UX Fixes

- app/src/MarketTable/MarketRow/index.js
- app/src/MarketTable/MarketRow/marketRow.scss
- app/src/MarketTable/marketTable.scss
- app/src/Root/root.scss
- app/src/conf/config.rinkeby.json
- package-lock.json
- package.json
Implements https://gitlab.gnosisdev.com/prediction-markets/requirements/issues/120
> Implement Datasource/Description on Categorical Markets

- app/src/Routes.js
- app/src/store/index.js
- app/src/store/reducers.js
- app/src/views/kyc/Sow.js
Add some feedback on error
Add redirect after KYC is correctly setted
> Add fixes to sow form

- app/src/Sidebar_WithScalar/Buy/buy.scss
- app/src/Sidebar_WithScalar/Buy/index.js
- app/src/components/Formatting/PercentageFormat.js
@cag Please take a look if I got this right?
> Feature: Market Profit Loss/Win Simulator Slider

- app/src/Header/index.js
- app/src/components/Menu.js
- app/src/components/menu.scss
- app/webpack.config.js
Allows redirect to `sight.pm/#markets` when pressing either the logo or the markets button.
> Feature: Markets Button and Header redirect

- app/src/Sidebar/Positions/index.js
Just a minor review of hotfix #92
> Simplify allEarningCalculations and remove console.log

- app/src/Sidebar/Buy/buy.scss
- app/src/Sidebar/Positions/positions.scss
- app/src/components/Footer/footer.scss
Fix sidebar and positions layout.
> Fix sidebar overflow issues

- app/src/Root/index.js
Fix an typo issue with WHITELIST_ENABLE
> Fix WHITELIST_ENABLE check

- app/src/MarketTable/MarketRow/index.js
- app/src/MarketTable/MarketRow/marketRow.scss
- app/src/Root/root.scss
- app/src/Sidebar/sidebar.scss
Fix market details overlap with footer if description is too long
Fix mobile view big scroll
> Fix #133 and other layout fixes.

- app/src/MarketTable/CategoricalMarketTable/MarketRow/index.js
- app/src/MarketTable/CategoricalMarketTable/MarketRow/probabilityChart.js
- app/src/MarketTable/CategoricalMarketTable/index.js
- app/src/MarketTable/ScalarMarketTable/index.js
- app/src/Root/index.js
- app/src/Routes.js
- app/src/api/thegraph.js
- app/src/components/Graph.js
- app/src/index.js
- app/src/loadContracts.js
- app/src/repositories/ConditionalTokensRepo/index.js
- app/src/repositories/MarketMakersRepo/index.js
- app/src/utils/make-loadable.js
Refactor app loading to call web3 load only once
> Add posibility to get market maker address from URL

- app/src/Sidebar/components/Resolved/index.js
- app/src/Sidebar/components/Sell/Positions.js
- app/src/Sidebar/components/Sell/positions.scss
- app/src/components/Graph/index.js
- app/src/conf/config.rinkeby.json
Due to an accident, Redeeming was not included in the resolved sidebar view.
> Hotfix: Add Redeeming again

- app/src/Header/index.js
- app/src/MarketTable/ScalarMarketTable/index.js
- app/src/Root/index.js
- app/src/Sidebar/components/CategoricalBuy/index.js
- app/src/Sidebar/components/Resolved/index.js
- app/src/Sidebar/components/ScalarBuy/index.js
- app/src/Sidebar/components/ScalarBuy/profitSimulator.js
- app/src/Sidebar/components/Sell/Positions.js
- app/src/Sidebar/components/Sell/index.js
- app/src/Sidebar/index.js
- app/src/api/thegraph.js
- app/src/components/UserWallet.js
- app/src/conf/config-thegraph.js
- app/src/hooks/useGlobalState.js
- app/src/index.js
- app/src/services/ConditionalTokensService/ConditionalTokensService.js
- app/src/services/ConditionalTokensService/index.js
- app/src/store/globalStateReducer.js
- app/src/store/globalStore.js
- app/src/utils/scalar.js
- package-lock.json
- package.json
Use react context to handle app main state
Move some logic to service in order to simplify data handling in componets
Clean unnecessary data from components
> Use react context to handle state

- app/src/Root/index.js
- app/src/Sidebar/components/Resolved/Redeem.js
- app/src/Sidebar/components/Resolved/index.js
- app/src/Sidebar/components/Sell/Positions.js
- app/src/Sidebar/components/Sell/SellForm.js
- app/src/Sidebar/components/Sell/index.js
- app/src/Sidebar/components/Sell/positions.scss
- app/src/services/ConditionalTokensService/ConditionalTokensService.js
Refactor sell and redeem component and enable to show resolution state even if an account is not connected
Separate redeem logic to own component
> Refactor sell and redeem components

- app/src/Root/index.js
- app/src/api/operator.js
- app/src/components/UserWallet.js
- app/src/loadContracts.js
- app/src/repositories/ConditionalTokensRepo/index.js
- app/src/repositories/MarketMakersRepo/index.js
- app/src/services/ConditionalTokensService/index.js
- app/src/utils/ContractLoader.js
- app/src/utils/getIdsUtil.js
- app/src/utils/getMarketsData.js
- app/src/utils/position-groups.js
- app/src/utils/web3.js
App takes few seconds to show information. We want to show information as soon as available.
Blockchain queries are slow, and we can get some more information from Sight Operator.
We will refactor the process to separate operator fetching and necessary blockchain queries. Will try to show information as soon as available, while waiting for blockchain initialization to finish.
> Loading time optimization

- app/src/Modals/KYC/steps/Approved.js
- app/src/Modals/KYC/steps/EuropeResident.js
- app/src/Modals/KYC/steps/Info.js
- app/src/Modals/KYC/steps/Nationality.js
- app/src/Modals/KYC/steps/Pending.js
- app/src/Modals/KYC/steps/Personal.js
- app/src/Modals/KYC/steps/Rejected.js
- app/src/Modals/KYC/steps/SOW.js
- app/src/Modals/KYC/steps/Tier2Request.js
- app/src/Modals/Transactions/index.js
- app/src/components/UserWallet.js
- app/src/views/kyc/tier2/index.js
This PR closes ticket gitlab/114 to fix wording for the KYC/Tier flow and to ensure it's consistent throughout the application
- See the Slidedeck attached to the ticket
/
> Task #114: Change Wording for KYC
